### ISSUE TITLE
security issue: user/pass, sql host

### ISSUE THREAD

**Issue by Parker-Wallace** [Crunchymcbones/Demo-store#18]
can we add a small section for user input where they enter the host, user, and password for the used SQL, at best we need to move the user and password from controller.py such that it can be edited if the users password and hostname are different.

ideally I would like something along the lines of a small login page where you enter those values.

thanks!

**Comment by Joshua-Crocker** [comment]
Not an issue

**Comment by Joshua-Crocker** [comment]
This is a feature, not a issue
